services:

  _defaults:
    autowire: true
    autoconfigure: true
  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['command']

  Atoolo\Deployment\Service\StopWorkerOnRedeployListener:
    arguments:
      - '%kernel.cache_dir%'

  Atoolo\Deployment\Service\Deployer:
    arguments:
      - '@logger'

  Atoolo\Deployment\Console\Command\DeployCommand:
    arguments:
      - '@Atoolo\Deployment\Service\Deployer'

  Atoolo\Deployment\Controller\DeployController:
    arguments:
      - '@Atoolo\Deployment\Service\Deployer'
